// templates/svelte/src/App.svelte
<script lang="ts">
  import { initController } from 'controller';
  import ConnectSample from './components/ConnectSample.svelte';
  import QuerySample from './components/QuerySample.svelte';
  import TxSample from './components/TxSample.svelte';
  
  let initialized = false;
  
  initController().then(() => {
    initialized = true;
  });
</script>

{#if !initialized}
  <div>Initializing...</div>
{:else}
  <ConnectSample />
  <QuerySample />
  <TxSample />
{/if}

// templates/lit/src/app.ts
import { initController } from 'controller';
import { html, render } from 'lit';
import './components/connect-sample';
import './components/query-sample';
import './components/tx-sample';

const container = document.querySelector('#app') as HTMLElement;

render(html`<div>Initializing...</div>`, container);

initController().then(() => {
  render(
    html`
      <connect-sample></connect-sample>
      <query-sample></query-sample>
      <tx-sample></tx-sample>
    `,
    container,
  );
});
